development:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL'] %>

test:
  clients:
    default:
      database: lead_generator_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      uri: <%= ENV['DATABASE_URL'] %>
